### ISSUE TITLE
lenke til ytterligere dokumentasjon fungerer ikke

### ISSUE THREAD

**Issue by aberner** [digipost/printability-validator#1]
i readme fila er det en referanse til mer dokumentasjon på url: https://www.digipost.no/plattform/masseutsendelser/print

Denne url'n ser ikke ut til å fungere, man blir bare ført til førstesiden på digipost.no

**Comment by runeflobakk** [comment]
Takk for heads-up. Fikset i 3c1609108a52a7316ae5d85a106eabdb2acd15b9
