### ISSUE TITLE
Dokument med Type3-fonter validerer ikke

### ISSUE THREAD

**Issue by stendavid** [digipost/printability-validator#13]
Den vedlagte PDF'en er PDF/A-1A med Type3-fonter. Validatorn feiler med meldingen
> The document refers to a non-standard font that is not included in the PDF.
selv om fontene er inkludert.

[simple-type3.pdf](https://github.com/digipost/printability-validator/files/3540772/simple-type3.pdf)

I følge en samtale vi hade med Digipost support virket det som om Type3-fonter er støttet og ville virke om de deaktiverte valideringen, men det vil vi ikke gjerne gjøre. Er det mulig å få det endret i validatorn?

**Comment by eivinhb** [comment]
Det har vært litt frem og tilbake her over en lengre periode. Men konklusjonen fra print-leverandøren er at de _kan_ støtte type3-fonter, men vil ikke gjøre det. Det noe med prosesseringen før utskrift og optimaliseringen som skjer.
Benytt truetype-fonter og embedd de i pdf-en.
