### ISSUE TITLE
Eksempel på gyldig PDF validerer ikke 

### ISSUE THREAD

**Issue by aberner** [digipost/printability-validator#2]
På følgende side har dere en lenke til en PDF som skal være gyldig.
ref: https://www.digipost.no/plattform/annet/print kapitel 2 punkt 2.
Lenke til PDF'n: https://www.digipost.no/dokumenter/platform/gyldig-for-print.pdf

Denne PDF'n validerer ikke og gir feilmeldingen:
    "PDF-dokumentet har for liten venstremarg. Minimum venstremarg er 18 mm."

Dette kommer muligens fordi det er en rød rute som beskriver hvor strekkoden legges inn.
Dokumentasjonen må oppdateres slik at dere har eksempel PDF'r som faktisk validerer, og at denne eksempel fila ikke har teksten: "Dette er et eksempel på et PDF dokument som er gyldig for print via 
Digipost"

**Comment by fredrikbach** [comment]
Takk @aberner Dette er jo litt forvirrende (fra vår side). Tror den opprinnelige tanken med det dokumentet var å da beskrive hvorfor den validerer, men det bli litt rart når den faktisk ikke validerer som resultat av det. Vi bytter ut PDFen med en annen som faktisk validerer. Igjen, takk for at du sier ifra om dette.

**Comment by aberner** [comment]
takk, det blir bra. Det er fint med en pdf som beskriver utskriften og viser hvor strekkoden kommer, men nå ble den faktisk brukt av en avsender for å teste valideringsbiblioteket og da ble det litt feil. 

Så PDF-n kan være fint å ha den, men da med en annen tekst, for å tydelig si i fra at denne PDF'n ikke validerer men kun beskriver utskriftsformatet.
