### ISSUE TITLE
Hvor mange sider er tillatt i utskriftstjenesten?

### ISSUE THREAD

**Issue by aberner** [digipost/printability-validator#3]
- https://github.com/digipost/printability-validator/blob/master/README.md
 - Her oppgis det at Maks sideantall på PDF dokumentet er 14 sider.
- https://www.digipost.no/plattform/annet/print
 - For automatisk konvoluttering må antall sider i dokumentet ikke overstige tolv sider.

Hva er riktig antall?
Er det snakk om antall sider eller antall ark?
Er dette antall sider/ark fra avsender eks forsidearket eller totalt antall inklusiv forsidearket?

**Comment by runeflobakk** [comment]
Hei,

Det er 14 som er maks antall totalt _sider_ i innsendt dokument (altså eksklusiv forsideark). Avsender skal ikke trenge å forholde seg til å vite om ev. ekstra ark som blir lagt til, eller om det er snakk om enkel- eller dobbelsidig print. Grensen er egentlig litt "soft" og eksisterer som en safety-hatch dersom man plutselig skulle forsøke å sende en PDF med en avsindig mengde sider. Dette er default-validering for avsendere som integrerer direkte med [Digipost sitt REST-API](https://www.digipost.no/plattform/api/v5/)
Har rettet til "14" på https://www.digipost.no/plattform/annet/print. 

Merk at for offentlig digital post gjøres det ikke validering av antall sider, ref https://github.com/digipost/printability-validator/blob/master/README.md#for-avsendere-som-sender-til-utskrift-via-offentlig-sikker-digital-post-sdp-meldingsformidlertjeneste. (Det er ikke _super_-innlysende fra instansiering av en `new PdfValidationSettings(false, true, false, true)` at det resulterer i at sidenantall-validering er skrudd av p.g.a. det gedigne anti-patternet med X antall boolean literals som metodeargumenter.)

Valideringen som gjøres for offentlig digital post som går til utskrift er kun at fonter må være embedded, samt at PDF-versjon ikke er høyere 1.5f. Dette er default, og går an å stille på per avsender.

**Comment by aberner** [comment]
Takk for info.
Jeg skjønner at denne infoen er mest for private avsendere, uansett greit at det er riktig.

Når du tar opp valideringene av PDF versjon.
Er det fortsatt gjeldende? Dere støtter vel høyere versjoner nå? (Ja det er vel et eget issue)

**Comment by runeflobakk** [comment]
Ja, validering av PDF-versjon er fortsatt gjeldende, og er p.t. begrenset til maks 1.5f. Det jobbes med å få til støtte for 1.7, men for å offisielt støtte dette kreves en del jobb bl.a. med testing av dokumenter.

Likevel, i de aller aller fleste tilfeller så går det helt greit å sende versjoner over 1.5f til utskrift, men vi har ikke gått ut med at vi _offisielt_ støtter dette enda. Derfor har vi mulighet til å per avsender skru av validering av PDF-versjon også, og kan gjøre dette på forespørsel dersom ønskelig av avsender. Da vil man typisk kjøre litt testing av postsending til utskrift for å gjøre en liten sanity-sjekk av typiske PDF-dokumenter med versjon _> 1.5f_ avsender ønsker å sende. Dette koordineres per i dag case-by-case.

Vi har til nå hatt én _offentlig_ avsender vi har testet å skru av validering av PDF-versjon i testmiljø, men har ikke skrudd noe på dette i produksjon.
